name: Update README with Date & Snake

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate date
        run: |
          echo "LAST_UPDATED=$(date -u '+%b %d, %Y • Week %V')" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/<!--TIME-->.*<!--END-->/<!--TIME-->$LAST_UPDATED<!--END-->/g" README.md

      - name: Commit & Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "⏰ Update time"
          git push
